##  Linear algebra 
Plan:

* Vector operations
* Multiplication
    * Vector-vector multiplication
    * Matrix-vector multiplication
    * Matrix-matrix multiplication
* Identity matrix
* Inverse

In [ ]:
  $$
  w = (X^T X)^{-1} X^T y
  $$

In [1]:
import numpy as np

## Vector operations

In [3]:
u =np.array([2,2,3,4])

  $$
  U = U * 2
  $$

In [5]:
v = np.array([1, 0, 0, 2])

  $$
  X = U * V
  $$

In [7]:
X = u*v
X 

array([2, 0, 0, 8])

## Multiplication

$$
\sum_{i=1}^{T} \varepsilon_i v_i
$$

In [11]:
def vector_vector_multiplication(u,v):
    assert v.shape == u.shape
    n= v.shape[0]
    result =0.0 
    for i in range(n):
        result = result + u[i]*v[i]
    return result
   

In [12]:
vector_vector_multiplication(u,v)

np.float64(10.0)

In [13]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [14]:
def matrix_vector_multiplication(U ,v):
    assert v.shape[0] == U.shape[1]
    num_row = U.shape[0]
    result = np.zeros(num_row)
    for i in range(num_row):
        result[i] = vector_vector_multiplication(U[i] , v)
    return result

In [15]:
matrix_vector_multiplication(U ,v)

array([14.,  5.,  5.])

In [16]:
U.dot(v)

array([14,  5,  5])

In [17]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])

In [19]:
def matrix_matrix_multiplication(U,V):
    assert V.shape[0] == U.shape[1]
    num_row =U.shape[0]
    num_col = V.shape[1]
    result =np.zeros((num_row ,num_col))
    for i in range(num_col):
        vi =V[:,i]
        Uvi = matrix_vector_multiplication(U,vi)
        result[:,i]=Uvi

    return result
    

In [20]:
matrix_matrix_multiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [21]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity matrix

In [30]:
I =np.eye(3)

In [31]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [32]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Inverse

In [34]:
Vs =V[[0,1,2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [36]:
V_inv=np.linalg.inv(Vs)
V_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [37]:
V_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])