#  Introduction to NumPy


Plan:

* Creating arrays
* Multi-dimensional arrays
* Randomly generated arrays
* Element-wise operations
    * Comparison operations
    * Logical operations
* Summarizing operations

In [1]:
import numpy as np

## Creating arrays


In [3]:
zeros_arr = np.zeros(5)
zeros_arr

array([0., 0., 0., 0., 0.])

In [4]:
ones_arr =np.ones(5)
ones_arr

array([1., 1., 1., 1., 1.])

In [6]:
arr = np.full(10,3)
arr

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [8]:
arr_1 =np.array([1,2,8,9,6,3,8])
arr_1

array([1, 2, 8, 9, 6, 3, 8])

In [9]:
arr_1[5]

np.int64(3)

In [12]:
arr_1[5]=10
arr_1[5]

np.int64(10)

In [13]:
arr_2 = np.arange(10)
arr_2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr_3= np.linspace(0,100,11)
arr_3

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dimensional arrays


In [17]:
arr_4 = np.zeros((4,4))
arr_4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
arr_5 =np.ones((4,4))
arr_5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
arr_6 =np.array([[1., 1., 1., 1.],
                 [0., 0., 0., 0.],
                 [0., 0., 0., 0.],
                 [1., 1., 1., 1.]])
arr_6

array([[1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.]])

In [22]:
arr_6[1,1]=12
arr_6

array([[ 1.,  1.,  1.,  1.],
       [ 0., 12.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.]])

In [23]:
arr_6[1]

array([ 0., 12.,  0.,  0.])

In [25]:
arr_6[:,2]

array([1., 0., 0., 1.])

## Randomly generated arrays


In [29]:
np.random.seed(42)
arr_7 = np.random.rand(5,5)
arr_7

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998]])

In [31]:
arr_8 =100 *  np.random.rand(5,5)
arr_8

array([[49.51769101,  3.43885211, 90.93204021, 25.87799816, 66.25222844],
       [31.17110761, 52.00680212, 54.67102793, 18.48544555, 96.95846278],
       [77.51328234, 93.94989416, 89.48273504, 59.78999788, 92.1874235 ],
       [ 8.84925021, 19.59828624,  4.52272889, 32.53303308, 38.86772897],
       [27.13490318, 82.87375092, 35.67533267, 28.09345097, 54.26960832]])

In [30]:
arr_9 = np.random.randint(low=0 ,high=100,size=(5,5))
arr_9

array([[46, 61, 50, 54, 63],
       [ 2, 50,  6, 20, 72],
       [38, 17,  3, 88, 59],
       [13,  8, 89, 52,  1],
       [83, 91, 59, 70, 43]])

## Element-wise operations


In [33]:
arr_10 = np.arange(5)
arr_10

array([0, 1, 2, 3, 4])

In [35]:
arr_11 = arr_10 +5 # or any ops + , - , * , /

arr_11

array([5, 6, 7, 8, 9])

In [36]:
arr_12 = (10 + (arr_11*2))**3
arr_12

array([ 8000, 10648, 13824, 17576, 21952])

In [37]:
arr_11+ arr_12+ arr_10

array([ 8005, 10655, 13833, 17587, 21965])

## Comparison operations

In [38]:
arr_11< arr_12

array([ True,  True,  True,  True,  True])

In [40]:
arr_11>= 500

array([False, False, False, False, False])

## Summarizing operations

In [41]:
a=arr_11
a

array([5, 6, 7, 8, 9])

In [42]:
a.max()

np.int64(9)

In [43]:
a.mean()

np.float64(7.0)

In [44]:
a.sum()

np.int64(35)

In [45]:
a.std()

np.float64(1.4142135623730951)